<a href="https://colab.research.google.com/github/WhyJYJ/deeplearning-for-everyone/blob/master/ch17/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 17장 딥러닝을 이용한 자연어 처리
17-2 영화 리뷰가 긍정적인지 부정적인지 예측하기

In [0]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

In [0]:
# 텍스트 리뷰 자료를 지정
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [3]:
# 토큰화 
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [4]:
# 토큰 인덱스로 새 배열 생성
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


**패딩(padding) 과정**</br>
딥러닝 모델에 입력을 하려면 학습 데이터의 길이가 동일해야하는데 이처럼 길이를 똑같이 맞춰 주는 작업</br>

**keras의 pad_sequence 함수**</br>
=> 원하는 길이보다 짧은 부분은 숫자 0으로 채워주고, 긴 데이터는 잘라서 같은 길이로 맞춤


In [5]:
# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줌
padded_x = pad_sequences(x, 4) 
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


**단어 임베딩** : 원-핫 인코딩을 그대로 사용하면 벡터의 길이가 너무 길어지는 문제가 있음. 이를 해결하기 위해 각 단어 간의 유사도를 계산하여 주어진 배열을 정해진 길이로 압축.

**Embedding 함수** :  적절한 크기로 배열을 바꾸어 주기 위해 단어 간 최적의 유사도를 계산해줌

In [6]:
#임베딩에 입력될 단어의 수를 지정
word_size = len(token.word_index) +1
 
#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4)) # 입력, 출력, 단어 수
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6925 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6905 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6885 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6865 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6844 - accuracy: 0.6000
Epoch 6/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6824 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6804 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6784 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6764 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6744 - accuracy: 0.8000
Epoch 11/20
1/1 [======================